package com.ironcoffee.retrograde.chunk;

import com.ironcoffee.retrograde.Main;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.StringTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.EmptyBlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.material.MapColor;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * Reads a chunk straight out of the region file, for chunks the server has
 * explored but isn't currently holding in memory.
 *
 * Without this the map only ever shows the handful of chunks inside the
 * server's loaded radius, so walking away turns the map you just filled in
 * back to grey - the one thing that made it feel broken next to a normal
 * minimap mod, and the thing that made "select a region and regen it"
 * useless past a few hundred blocks.
 *
 * <h2>Why this decodes the NBT by hand</h2>
 *
 * The obvious move is to call whatever deserializer vanilla uses, and that's
 * exactly what doesn't work across this mod's version range: 26.x has
 * SerializableChunkData#parse, which is side-effect free and ideal, and
 * 1.20.1 has no equivalent at all - only ChunkSerializer#read, which wants a
 * PoiManager and mutates it on the way past. So decoding the format directly
 * is the less fragile of two awkward options, not a clean one.
 *
 * The container is the same everywhere - "sections" -> "block_states" ->
 * "palette"/"data", with the same packed-long encoding, whose bit widths were
 * checked against ~600 real sections across 1.20.1 and 26.3 without a
 * mismatch. The palette *entries* are not: 26.3 made BlockState's codec
 * {@code Codec.either(byNameCodec, FULL_CODEC)}, so default states became bare
 * strings and the rest moved from {@code Name} to {@code id}. An earlier
 * version of this class assumed otherwise and read every 26.3 chunk as solid
 * air, which drew as black squares with no biome and no ores. See
 * {@link #paletteName} - that method is the whole of the difference, and the
 * reason nothing here should assume a shape it hasn't checked.
 *
 * Block states are resolved to {@code defaultBlockState()} and their
 * properties thrown away. Map color and ore-ness are both per-block in
 * vanilla and in every modded ore worth counting, so the properties would
 * cost a full state lookup per palette entry to change nothing.
 *
 * Decoding runs off the server thread - it touches only the block registry,
 * tag membership, and the level's immutable height range. The region read
 * that feeds it does not: {@link #read} must be called from the server
 * thread, though it returns immediately, since the read itself is async.
 */
public final class SavedChunkReader {
	/**
	 * 1.18's chunk format (DataVersion 2825) is the oldest one shaped like
	 * the one decoded here. Anything older is a chunk generated by a much
	 * older game and never re-saved since; rather than decode it wrong, the
	 * map treats it as if it had never been generated.
	 */
	private static final int MIN_DATA_VERSION = 2825;

	private static final int SECTION_SIZE = 16;
	private static final int SECTION_BLOCKS = SECTION_SIZE * SECTION_SIZE * SECTION_SIZE;
	private static final long[] NO_LONGS = new long[0];

	/** Terrain colors laid out exactly like {@link ChunkTerrainSample#sample}, plus the same info {@link ChunkResourceInfo#scan} returns. */
	public record Saved(int[] colors, ChunkResourceInfo.Inspection inspection) {}

	private SavedChunkReader() {}

	/**
	 * Null result means there's nothing saved at those coordinates, or what's
	 * there is too old or too broken to read - either way, a chunk the map
	 * should draw as never generated rather than pretend to know about.
	 *
	 * Call on the server thread. The returned future completes on a
	 * background thread once the region read lands.
	 */
	public static CompletableFuture<Saved> read(ServerLevel level, ChunkPos pos) {
		return level.getChunkSource().chunkMap.read(pos)
			.thenApplyAsync(tag -> tag.map(root -> decode(level, pos, root)).orElse(null))
			.exceptionally(error -> {
				Main.LOGGER.debug("Retrograde: couldn't read saved chunk {}", pos, error);
				return null;
			});
	}

	private static Saved decode(ServerLevel level, ChunkPos pos, CompoundTag root) {
		try {
			return decodeChecked(level, pos, root);
		} catch (RuntimeException error) {
			// A corrupt or unexpected chunk is worth a log line and nothing
			// more - one bad chunk shouldn't take the whole map down.
			Main.LOGGER.debug("Retrograde: couldn't decode saved chunk {}", pos, error);
			return null;
		}
	}

	private static Saved decodeChecked(ServerLevel level, ChunkPos pos, CompoundTag root) {
		// Anything short of "full" is a chunk still partway through
		// generation - real block data, but not the terrain you'd see if you
		// walked there, so not worth showing.
		if (!isFullyGenerated(stringOf(root, "Status"))) return null;
		if (intOf(root, "DataVersion") < MIN_DATA_VERSION) return null;

		ListTag sectionTags = listOf(root, "sections");
		if (sectionTags.isEmpty()) return null;

		Map<Integer, Section> sections = new HashMap<>();
		int topSectionY = Integer.MIN_VALUE;
		for (int i = 0; i < sectionTags.size(); i++) {
			CompoundTag sectionTag = compoundAt(sectionTags, i);
			Section section = readSection(sectionTag);
			if (section == null) continue;
			int sectionY = byteOf(sectionTag, "Y");
			sections.put(sectionY, section);
			if (!section.uniformAir() && sectionY > topSectionY) {
				topSectionY = sectionY;
			}
		}
		if (topSectionY == Integer.MIN_VALUE) return null;

		//? if >=26 {
		/*int minY = level.getMinY();
		int chunkX = pos.x();
		int chunkZ = pos.z();
		*///?} else {
		int minY = level.getMinBuildHeight();
		int chunkX = pos.x;
		int chunkZ = pos.z;
		//?}

		int[] colors = new int[ChunkTerrainSample.SIZE * ChunkTerrainSample.SIZE];
		int centerSurfaceY = minY;
		BlockPos.MutableBlockPos cursor = new BlockPos.MutableBlockPos();

		for (int lz = 0; lz < ChunkTerrainSample.SIZE; lz++) {
			int previousHeight = Integer.MIN_VALUE;
			for (int lx = 0; lx < ChunkTerrainSample.SIZE; lx++) {
				int worldX = chunkX * ChunkTerrainSample.SIZE + lx;
				int worldZ = chunkZ * ChunkTerrainSample.SIZE + lz;
				int y = topSectionY * SECTION_SIZE + SECTION_SIZE - 1;
				MapColor mapColor = MapColor.NONE;

				while (y >= minY) {
					Section section = sections.get(Math.floorDiv(y, SECTION_SIZE));
					// A section of nothing but air can't contribute a color,
					// so drop straight past it instead of testing sixteen
					// identical blocks. Above the terrain that's most of the
					// column, which is what keeps this scan cheap.
					if (section == null || section.uniformAir()) {
						y = Math.floorDiv(y, SECTION_SIZE) * SECTION_SIZE - 1;
						continue;
					}
					BlockState state = section.blockAt(lx, Math.floorMod(y, SECTION_SIZE), lz);
					cursor.set(worldX, y, worldZ);
					mapColor = state.getMapColor(EmptyBlockGetter.INSTANCE, cursor);
					if (mapColor != MapColor.NONE) break;
					y--;
				}

				// Same hillshade as ChunkTerrainSample: compare against the
				// column to the west so the two paths produce the same
				// picture for the same terrain.
				MapColor.Brightness brightness;
				if (previousHeight == Integer.MIN_VALUE || y == previousHeight) {
					brightness = MapColor.Brightness.NORMAL;
				} else if (y > previousHeight) {
					brightness = MapColor.Brightness.HIGH;
				} else {
					brightness = MapColor.Brightness.LOW;
				}
				previousHeight = y;

				if (lx == 8 && lz == 8) centerSurfaceY = y;

				//? if >=26 {
				/*colors[lz * ChunkTerrainSample.SIZE + lx] = mapColor.calculateARGBColor(brightness) | 0xFF000000;
				*///?} else {
				colors[lz * ChunkTerrainSample.SIZE + lx] = mapColor.calculateRGBColor(brightness) | 0xFF000000;
				//?}
			}
		}

		return new Saved(colors, new ChunkResourceInfo.Inspection(
			tallyOres(sections.values()),
			biomeAt(sections.get(Math.floorDiv(centerSurfaceY, SECTION_SIZE)), centerSurfaceY)));
	}

	/**
	 * 1.20 namespaced the status values that earlier versions wrote bare, and
	 * a world can hold chunks written by both.
	 */
	private static boolean isFullyGenerated(String status) {
		return "full".equals(status) || "minecraft:full".equals(status);
	}

	private static List<ChunkResourceInfo.Entry> tallyOres(Iterable<Section> sections) {
		Map<Block, Integer> tally = new HashMap<>();
		for (Section section : sections) {
			if (section.uniformAir()) continue;
			// Count palette slots rather than block states: the whole palette
			// is usually a few dozen entries for 4096 positions, so the
			// ore test runs once per distinct block instead of per block.
			int[] counts = section.countByPaletteIndex();
			for (int i = 0; i < counts.length; i++) {
				if (counts[i] == 0) continue;
				BlockState state = section.palette()[i];
				Block block = state.getBlock();
				if (ChunkResourceInfo.isOre(state, block)) {
					tally.merge(block, counts[i], Integer::sum);
				}
			}
		}

		List<ChunkResourceInfo.Entry> entries = new ArrayList<>();
		tally.forEach((block, count) -> entries.add(new ChunkResourceInfo.Entry(block, count)));
		entries.sort((a, b) -> b.count() - a.count());
		return entries;
	}

	/** Biome at the chunk's center column, matching what ChunkResourceInfo reports for a loaded chunk. */
	private static ResourceLocation biomeAt(Section section, int surfaceY) {
		if (section == null || section.biomePalette().length == 0) return null;
		int index = 0;
		if (section.biomePalette().length > 1 && section.biomeData().length > 0) {
			// Biomes are stored one entry per 4x4x4 cell, y-major then z then
			// x, same ordering as blocks just at a quarter the resolution.
			int cellY = Math.floorMod(surfaceY, SECTION_SIZE) / 4;
			index = unpackOne(section.biomeData(), cellY * 16 + 2 * 4 + 2,
				bitsPerEntry(section.biomePalette().length, 1));
		}
		if (index < 0 || index >= section.biomePalette().length) return null;
		return ResourceLocation.tryParse(section.biomePalette()[index]);
	}

	private static Section readSection(CompoundTag sectionTag) {
		CompoundTag blockStates = compoundOf(sectionTag, "block_states");
		ListTag paletteTag = listOf(blockStates, "palette");
		if (paletteTag.isEmpty()) return null;

		BlockState[] palette = new BlockState[paletteTag.size()];
		for (int i = 0; i < palette.length; i++) {
			palette[i] = blockFor(paletteName(paletteTag, i)).defaultBlockState();
		}
		// A single-entry palette carries no data array at all - the whole
		// section is that one block, which for most of a column is air.
		char[] blocks = unpack(longsOf(blockStates, "data"), SECTION_BLOCKS, palette.length, 4);

		CompoundTag biomes = compoundOf(sectionTag, "biomes");
		ListTag biomePaletteTag = listOf(biomes, "palette");
		String[] biomePalette = new String[biomePaletteTag.size()];
		for (int i = 0; i < biomePalette.length; i++) {
			biomePalette[i] = paletteName(biomePaletteTag, i);
		}

		return new Section(palette, blocks, biomePalette, longsOf(biomes, "data"));
	}

	/**
	 * Pulls the registry name out of one palette entry, in any of the four
	 * shapes the game has written them in.
	 *
	 * 1.20.1 and 26.1 always write a compound keyed {@code Name}. 26.3 changed
	 * BlockState's codec to {@code Codec.either(byNameCodec, FULL_CODEC)}, so a
	 * state with no non-default properties now serializes as a bare string and
	 * only the rest keep a compound - which is keyed {@code id}, not
	 * {@code Name}. NBT lists are homogeneous, so the moment one entry in a
	 * section needs a compound, the bare strings beside it get wrapped as
	 * {@code {"": "minecraft:stone"}} with the value under the empty key.
	 *
	 * Biome palettes are plain strings everywhere, but they go through here too
	 * rather than get their own reader - there's no reason to assume they'll
	 * stay exempt from the same change.
	 *
	 * The instanceof is doing real work: 1.20.1's {@code ListTag#getString(int)}
	 * returns {@code tag.toString()} for a non-string element, not {@code ""},
	 * so a "try string, fall back to compound" reader would take the SNBT text
	 * of the whole compound as the block name and never reach the fallback.
	 */
	private static String paletteName(ListTag palette, int index) {
		if (palette.get(index) instanceof StringTag) return stringAt(palette, index);
		CompoundTag entry = compoundAt(palette, index);
		String name = stringOf(entry, "Name");
		if (name.isEmpty()) name = stringOf(entry, "id");
		if (name.isEmpty()) name = stringOf(entry, "");
		return name;
	}

	private static Block blockFor(String name) {
		ResourceLocation id = ResourceLocation.tryParse(name);
		if (id == null) return net.minecraft.world.level.block.Blocks.AIR;
		//? if >=26 {
		/*return BuiltInRegistries.BLOCK.getValue(id);
		*///?} else {
		return BuiltInRegistries.BLOCK.get(id);
		//?}
	}

	/**
	 * Unpacks Minecraft's paletted long array. Entries are padded so none
	 * ever straddles a long boundary, which is what makes this a shift and a
	 * mask rather than a bit-stream reader. Null means "no data array", i.e.
	 * every position is palette entry 0.
	 */
	private static char[] unpack(long[] data, int size, int paletteSize, int minBits) {
		if (paletteSize <= 1 || data.length == 0) return null;
		int bits = bitsPerEntry(paletteSize, minBits);
		int perLong = 64 / bits;
		long mask = (1L << bits) - 1;
		char[] out = new char[size];
		for (int i = 0; i < size; i++) {
			int longIndex = i / perLong;
			if (longIndex >= data.length) break;
			out[i] = (char) ((data[longIndex] >>> ((i % perLong) * bits)) & mask);
		}
		return out;
	}

	private static int unpackOne(long[] data, int index, int bits) {
		int perLong = 64 / bits;
		int longIndex = index / perLong;
		if (longIndex >= data.length) return 0;
		return (int) ((data[longIndex] >>> ((index % perLong) * bits)) & ((1L << bits) - 1));
	}

	private static int bitsPerEntry(int paletteSize, int minBits) {
		int bits = minBits;
		while ((1 << bits) < paletteSize) bits++;
		return bits;
	}

	/** One decoded section: its palette, and which palette entry sits at each position. */
	private record Section(BlockState[] palette, char[] blocks, String[] biomePalette, long[] biomeData) {
		boolean uniformAir() {
			return blocks == null && palette[0].isAir();
		}

		BlockState blockAt(int x, int y, int z) {
			if (blocks == null) return palette[0];
			int index = blocks[y * 256 + z * SECTION_SIZE + x];
			return index < palette.length ? palette[index] : palette[0];
		}

		int[] countByPaletteIndex() {
			int[] counts = new int[palette.length];
			if (blocks == null) {
				counts[0] = SECTION_BLOCKS;
				return counts;
			}
			for (char index : blocks) {
				if (index < counts.length) counts[index]++;
			}
			return counts;
		}
	}

	// ----- NBT accessors -----
	//
	// 26 moved every getter on CompoundTag and ListTag to an Optional-based
	// shape and dropped the element-type argument lists used to need. 26.1
	// and 26.3 are identical here, so this splits two ways, not three.

	//? if >=26 {
	/*private static ListTag listOf(CompoundTag tag, String key) { return tag.getListOrEmpty(key); }

	private static CompoundTag compoundOf(CompoundTag tag, String key) { return tag.getCompoundOrEmpty(key); }

	private static CompoundTag compoundAt(ListTag list, int index) { return list.getCompoundOrEmpty(index); }

	private static String stringOf(CompoundTag tag, String key) { return tag.getStringOr(key, ""); }

	private static String stringAt(ListTag list, int index) { return list.getStringOr(index, ""); }

	private static long[] longsOf(CompoundTag tag, String key) { return tag.getLongArray(key).orElse(NO_LONGS); }

	private static int intOf(CompoundTag tag, String key) { return tag.getIntOr(key, 0); }

	private static int byteOf(CompoundTag tag, String key) { return tag.getByteOr(key, (byte) 0); }
	*///?} else {
	// Untyped on purpose: a 26.3 block palette is a list of strings when every
	// state in the section is a default one and a list of compounds otherwise,
	// so asking getList for a specific element type silently drops half of them.
	private static ListTag listOf(CompoundTag tag, String key) {
		return tag.get(key) instanceof ListTag list ? list : new ListTag();
	}

	private static CompoundTag compoundOf(CompoundTag tag, String key) { return tag.getCompound(key); }

	private static CompoundTag compoundAt(ListTag list, int index) { return list.getCompound(index); }

	private static String stringOf(CompoundTag tag, String key) { return tag.getString(key); }

	private static String stringAt(ListTag list, int index) { return list.getString(index); }

	private static long[] longsOf(CompoundTag tag, String key) { return tag.getLongArray(key); }

	private static int intOf(CompoundTag tag, String key) { return tag.getInt(key); }

	private static int byteOf(CompoundTag tag, String key) { return tag.getByte(key); }
	//?}
}
